# Site settings
name: Dinmukhamed Tursynbay

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Codeforces
   url: https://codeforces.com/profile/DimmyT/
 - title: Blog
   url: http://codeforces.com/blog/DimmyT/
 - title: GitHub
   url: https://github.com/iitsdim/

#Any buzzword skills you want to include
skills:
 - C++
 - Python


#Work experience is required
works:
 - title: Competitive programming club
   start: 2015
   end: Ongoing
   role: Member
   description: I taught algorithms, created contests, and explained the solutions of contest problems to the members of club. I organized and held camp on programing.

#Education is required
education:
 - level: High school
   date: may 2020
   school: Almaty Bilim Innovation Lyceum

#This section is optional (as is the image link below)

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute



intro: |
  I am a 17 years old pupil from High school, who enjoy coding and problem-solving.
hobbies: 
 - Competitive programming
 - Football
 - Computer games
 - Video Editing
 - Magic tricks
 - Book reader

theme: jekyll-theme-hacker
