# Site settings
name: Dinmukhamed Tursynbay

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Codeforces
   url: https://codeforces.com/profile/DimmyT/
 - title: Blog
   url: http://codeforces.com/blog/DimmyT/
 - title: GitHub
   url: https://github.com/iitsdim/
 - title: Hackerrank
   url: https://www.hackerrank.com/dimash241/
 - title: Codechef
   url: https://www.codechef.com/users/dimash241/

#Any buzzword skills you want to include
skills:
 - C++
 - Wide Range of Algorithms
 - Python


#Work experience is required
works:
 - title: Competitive programming club
   start: 10.2015
   end: Ongoing
   role: Member
   description: I taught algorithms, created contests, and explained the solutions of contest problems to the members of club. I organized and held camp on programing.
 - title: Moscow Workshop Juniors (MWJ)
   start: 02.2019
   end: 03.2019
   role: Participant
   description: I learned types of algorithms as advanced math, flow, dominators tree and matroids; Attended Olympiad organized by MWJ and took 3rd place.
 - title: Video Editor
   start: 12.2017
   end: Ongoing
   role: Video Editor
   description: I was editing a video for customers (paid work). I did clip and present videos by cutting and effects video.
#Education is required
education:
 - level: High school
   date: may 2020
   school: Almaty Bilim Innovation Lyceum

#This section is optional (as is the image link below)

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute

Olympiadhonors: |
    <strong>IZHO</strong>: 15th International Zhautykov Olympiad, Silver Medal in Computer Science in 2019.<br/><br/>
    <strong>IOM</strong>: 4th International Olympiad of Metropolises, Silver Medal in IT, 3rd place in Team Scoring in 2019.<br/><br/>
    <strong>Tuymaada</strong>: 26th International Tuymaada Olympiad, Silver Medal in Informatics,Yakutia.<br/><br/>
    <strong>19th All-Russian Programming School Olympiad</strong>: It is a big competition team programming competition with 259 participant teams. My team's name is dab. I achieved 3-degree diploma on this Olympiad.<br/><br/>
    <strong>XI Eurasian Olympiad in Computer Science</strong>: It is a team olympiad with more than 200 participants. I am the winner of this olympiad. Competiton style is  ACM ICPC.<br/><br/>
    <strong>Technocup 2019</strong>: Technocup is a major olympiad for Russian-speaking high-school students, Second degree diploma in 2019.<br/><br/>
    <strong>National Olympiad in Informatics</strong>: Bronze Medal in 2018 and Gold Medal in 2019.<br/><br/>
    

intro: |
  I am a 17 years old pupil from High school, who enjoy coding and problem-solving.<br/><br/>
  Firstly, I would like to present some background information about myself. Since childhood, I have two interesting hobbies: football and legerdemain. I played football in almost every place where I was. In fact, when I was in olympiad Tuymaada, I created a team with other country delegations and won the tournament of football. Furthermore, I even have a goblet as the winner. Furthermore, I even have a goblet as the winner. Interest in magic tricks, I used in the school event where is I show plenty of which. Last five years, I found another pleasure for me - the IT Olympiad club. During this period, I made significant progress in computer science and showed great performance in many competitions at international and national levels. As one of the top achievers of my country in 2019, I was one of the fifteen students who qualified to be a participant in the International Olympiad in Informatics (IOI). Unfortunately for me, I was ranked 5th place after elimination olympiads results while the top 4 students participated in IOI 2019 in Baku.
hobbies: 
 - Competitive programming
 - Football
 - Computer games
 - Video Editing
 - Magic tricks
 - Book reader

theme: jekyll-theme-tactile
